### ISSUE TITLE
Line 60 issue

### ISSUE THREAD

**Issue by KO4LFZ** [craigerl/ygate#11]
I am setting this up on a Pi Zero W on a FTM-300.  I have made the correction to the serial port by adding placing the following in line 36  SERIAL_PORT = '/dev/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0' ## Linux

When I run the script I get the following:

  File "/home/KO4LFZ/./ygate.py", line 60
    SERIAL_PORT = '/dev/usb-Prolific_Technology_Inc._USB-Serial_Controller-if00-port0#
                  ^
SyntaxError: unterminated string literal (detected at line 60)

I have upgraded to python 3.12.2

**Comment by craigerl** [comment]
missing the close quote at the end of your device name.   should be using ttyUSB0 too?

**Comment by KO4LFZ** [comment]
No this is the error.

/home/KO4LFZ/./ygate.py:174: SyntaxWarning: invalid escape sequence '\['
  if (re.search('\[.*\] <UI.*>:', str(line))):     # Yaesu's nmea9-formatted suffix means we found a routing block
/home/KO4LFZ/./ygate.py:176: SyntaxWarning: invalid escape sequence '\['
  routing = re.sub(' \[.*\] <UI.*>:', ',qAO,' + USER + ':', routing)  # drop nmea/yaesu gunk, append us to routing block
Traceback (most recent call last):
  File "/home/KO4LFZ/./ygate.py", line 22, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

I have attached the script as a notepad file
[APRS.txt](https://github.com/craigerl/ygate/files/14548828/APRS.txt)

**Comment by craigerl** [comment]
from the readme,

If you see errors like missing modules, or "not defined", you might need additional python libraries. For example, if you see serial errors, make sure pyserial is installed. "sudo pip3 install pyserial"
