### ISSUE TITLE
Is This Still Maintained?  Looks like similar issue to previous.

### ISSUE THREAD

**Issue by maesoph** [craigerl/ygate#5]
I am new to HAM radio and my main activity is tracking APRS transmitters on my balloons - both high altitude and pico (around the world).  Running yGate with my Yeasu FTM-400 and it crashes at least once a day and needs to be restarted to recover.  It's running on a Raspberry Pi 3B.  A few successful packets and part of the error message is shown below.  Error message repeats until restarted.

Mike
KC3GMG
EMail:  aesoph_family@yahoo.com

N8GD-2>APOT21,NJ3T-4*,WIDE2-1,qAR,KC3GMG-10:!4022.44N/08042.13W# 13.6V 68F 
>>> Internet packet not gated:  N8GD-1>APU25N,N3FB-2*,WIDE2-1,qAR,KC3GMG-10:}N8GD-2>APOT21,TCPIP,N8GD-1*:!4022.44N/08042.13W# 13.6V 68F
N3KTX-5>BEACON,qAR,KC3GMG-10:MasonDixon A.P.R.S. Group AT 146.895- WITH I.R.L.P.#7070
KB3FCZ-2>APN391,NJ3T-4*,WIDE2,qAR,KC3GMG-10:!4022.01NS07955.33W#PHG7350 West Mifflin Digipeater
NU3S-7>APK102,N3FB-2,WIDE1*,WIDE3-3,qAR,KC3GMG-10:=4022.75N/08004.80W_260/004g008t062r   p   P023h92b10053KU2k
NU3S-7>APK102,N3FB-2,WIDE1,NJ3T-4*,qAR,KC3GMG-10:=4022.75N/08004.80W_260/004g008t062r   p   P023h92b10053KU2k
Traceback (most recent call last):
  File "/home/kc3gmg-10/Documents/yGate/ygate.py", line 117, in <module>
    sock.send(bytes(packet + '\r\n', 'utf-8'))  # spec calls for cr/lf, just lf worked in practice too
ConnectionResetError: [Errno 104] Connection reset by peer
Exception in thread Thread-27:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/kc3gmg-10/Documents/yGate/ygate.py", line 45, in send_my_position
    sock.send(bytes(position_string, 'utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 1266, in run
    self.function(*self.args, **self.kwargs)
  File "/home/kc3gmg-10/Documents/yGate/ygate.py", line 45, in send_my_position
    sock.send(bytes(position_string, 'utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
Exception in thread Thread-29:

**Comment by craigerl** [comment]
fixed in latest version

**Comment by maesoph** [comment]
Craig:
Got it installed finally and it seems to work great.  Sorry for delay, but I wanted this script to start automatically on boot up in it's own terminal window and it took me a while to figure that out.
Great job!  Five stars!!!!!!!
Mike

    On Saturday, March 9, 2024 at 08:32:26 PM EST, Craig Lamparter ***@***.***> wrote:  
 
 


fixed in latest version
